apiVersion: v1	
kind: Service	
metadata:	
  name: guestbook-ui	
  labels: 
    type: guestbook-ui
spec:	
  type: NodePort
  ports:	
  - port: 80	
    protocol: TCP
    name: http
    targetPort: http
  selector:	
    app: guestbook-ui
